import axios from 'axios'
const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:8000' })
const get = (u, p) => api.get(u, { params: p }).then(r => r.data)
const post = (u, b) => api.post(u, b).then(r => r.data)

export const getKpis = () => get('/api/kpis')
export const getSuppliers = () => get('/api/suppliers')
export const getSupplierRisk = id => get(`/api/suppliers/${id}/risk`)
export const getInventory = () => get('/api/inventory')
export const getStockoutRisk = pid => get(`/api/inventory/${pid}/stockout-risk`)
export const getProducts = () => get('/api/products')
export const getEvents = () => get('/api/events')
export const createEvent = b => post('/api/events', b)
export const getDemandForecast = pid => get(`/api/predictions/demand/${pid}`)
export const getImpact = id => get(`/api/impact/${id}`)
export const runSimulation = b => post('/api/simulator/run', b)
export const recommend = event_id => post('/api/optimizer/recommend', { event_id })
export const acceptPlan = (event_id, action_plan_rank) => post('/api/optimizer/accept', { event_id, action_plan_rank })
export const explain = (event_id, action_plan_rank) => post('/api/explain', { event_id, action_plan_rank })
export const getAudit = () => get('/api/audit')
export const getHeatmap = () => get('/api/inventory-heatmap')
export const getWarehouses = () => get('/api/warehouses')
